### ISSUE TITLE
Disallow automated testing

### ISSUE THREAD

**Issue by Arinerron** [EdOverflow/security-txt#20]
I'd suggest making a feature to disallow automated testing (burp, owasp tools, scanners, etc). Maybe:
```
Rate-limit: 0
```
? :)

**Comment by Arinerron** [comment]
Also, should I make a repository with a code for parsing these files in different languages?

**Comment by EdOverflow** [comment]
Hi @Arinerron,

I like your suggestion for disallowing automated testing. Setting the `Rate-limit:` to `0` should suffice. This will be made clear in the RFC.

> Also, should I make a repository with a code for parsing these files in different languages?

That is a fantastic idea and I would be happy to link to it in the README.md. :)

**Comment by EdOverflow** [comment]
Hi @Arinerron,

The `Rate-limit:` option is not in the Internet draft, because I decided to view security.txt as a means to contact a company if you find something, rather than something to encourage security researchers to hunt on the company's platform.

That said, I still look forward to seeing your parsers. You might want to take a look at what @tomnomnom has already done:

- https://github.com/tomnomnom/securitytxt
- https://github.com/tomnomnom/phpsecuritytxt
